/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {

   const val kaml: String = "com.charleskorn.kaml:kaml:_"

   const val gson: String = "com.google.code.gson:gson:_"

   const val h2: String = "com.h2database:h2:_"

   const val sshj: String = "com.hierynomus:sshj:_"

   const val kotest_runner_junit5: String = "io.kotest:kotest-runner-junit5:_"

   const val mockk: String = "io.mockk:mockk:_"

   const val commons_csv: String = "org.apache.commons:commons-csv:_"

   const val commons_email: String = "org.apache.commons:commons-email:_"

   const val httpclient: String = "org.apache.httpcomponents:httpclient:_"

   const val poi: String = "org.apache.poi:poi:_"

   const val poi_ooxml: String = "org.apache.poi:poi-ooxml:_"

   const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:_"

   const val kodein_di: String = "org.kodein.di:kodein-di:_"

   const val postgresql: String = "org.postgresql:postgresql:_"

   const val slf4j_api: String = "org.slf4j:slf4j-api:_"

   const val slf4j_log4j12: String = "org.slf4j:slf4j-log4j12:_"

   object Jackson {
      object Core {

         private const val groupId = "com.fasterxml.jackson.core"

         const val annotations = "$groupId:jackson-annotations:_"
         const val databind = "$groupId:jackson-databind:_"
         const val core = "$groupId:jackson-core:_"
      }

      object Dataformat {

         const val xml =
            "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:_"
      }

      object Module {

         private const val groupId = "com.fasterxml.jackson.module"
         const val kotlin = "$groupId:jackson-module-kotlin:_"
         const val jaxbAnnotations = "$groupId:jackson-module-jaxb-annotations:_"
      }
   }

   val jaxb = Jaxb

   object Jaxb {

      const val api = "javax.xml.bind:jaxb-api:_"
   }

   val arrow = Arrow

   object Arrow {

      private const val groupId = "io.arrow-kt"
      const val core = "$groupId:arrow-core:_"
   }

   val hoplite = Hoplite

   object Hoplite {

      private const val groupId = "com.sksamuel.hoplite"
      const val core = "$groupId:hoplite-core:_"
      const val yaml = "$groupId:hoplite-yaml:_"
   }
}
